### ISSUE TITLE
Minimize Global Options

### ISSUE THREAD

**Issue by npjc** [tidyverse/principles#11]
From Advanced R:

> global options make code harder to understand because they increase the number of lines you need to read to understand how a single line of code will behave.

**Comment by jennybc** [comment]
To go further, when are options OK (e.g. modify how things print or changing behaviour of "workflow" packages/functions) vs. not OK (e.g. modify return objects).

**Comment by hadley** [comment]
Maybe "non-local" inputs is a better general term — needs to include options and env vars.

**Comment by jennybc** [comment]
> Maybe "non-local" inputs is a better general term — needs to include options and env vars.

Does it include locale? Native encoding?

**Comment by hadley** [comment]
Yes!

**Comment by hadley** [comment]
Now in https://principles.tidyverse.org/args-hidden.html#args-hidden
