### ISSUE TITLE
Responsible use of `...`

### ISSUE THREAD

**Issue by jennybc** [tidyverse/principles#18]
Some topics:

  * Implications re: its placement in the signature
  * How to handle it inside the function
  * Documentation concerns

**Comment by hadley** [comment]
* `list()` vs `list2()`
* Naming the other arguments

**Comment by hadley** [comment]
`...` should be as far to the left as possible to force users to name arguments.

**Comment by hadley** [comment]
Matching `.prefixed` argument names with other functions — no need to do it.

**Comment by lionel-** [comment]
cc @rich-iannone, purrr was a historical error ;)
