### ISSUE TITLE
Naming functions: auto-completion and links

### ISSUE THREAD

**Issue by jennybc** [tidyverse/principles#38]
1. It can be nice to think about auto-completion when naming functions. The `str_` prefix of stringr makes a great example.

  2. If you care to link out, two favourites:

    * [I Shall Call It.. SomethingManager](https://blog.codinghorror.com/i-shall-call-it-somethingmanager/)
    * [The Poetry of Function Naming](http://blog.stephenwolfram.com/2010/10/the-poetry-of-function-naming/)

**Comment by hadley** [comment]
Moved to principles because I think this now fits better there.

**Comment by hadley** [comment]
@ctbrown I don't have a good sense for the right way to distinguish between vector and data frame focussed functions yet, but my feeling is that changing the naming convention is too big a hammer.

**Comment by ctbrown** [comment]
Agreed that it is a big hammer, no doubt.  The problem with collisions and confuse generally is going to get worse unless someone proposes a solution.  I do not have the audience.  You do.  So whenever you figure out what the standard is, the community will follow.
