### ISSUE TITLE
Default arguments

### ISSUE THREAD

**Issue by hadley** [tidyverse/principles#57]
Details arguments usually should have defaults. Data arguments usually shouldn't.

`init` in `reduce()` is weird because it's on the rhs of `...` but it doesn't have a default.

**Comment by jennybc** [comment]
I'm also interested in a policy about exposing unexported functions via default arguments. My instinct is that this is poor form, like talking about a party in front of people who are not invited. Either use `NULL` and force yourself to explain the default logic or use the helper and force yourself to export it.

**Comment by jennybc** [comment]
Related to #23 "Default values of function arguments" (or the titles need refining)

**Comment by hadley** [comment]
Do you happen to know a current function of ours that uses an unexported function for a default value?

**Comment by lionel-** [comment]
`vec_assert()` now calls `as_label()` in a default argument. It is not exported from vctrs but from rlang.

Using `NULL` here would make the code more complicated because the goal is to generate it lazily: https://github.com/r-lib/vctrs/issues/263#issuecomment-479638020

**Comment by jimhester** [comment]
readr did this until the last couple of releases, `show_progress()` was a default argument but was unexported.
